- hosts: app_server
  name: install docker on app app_server
  become: true
  vars:
    docker_package: docker
    docker_service: docker
    docker_compose_url: https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64
    docker_compose_path: /usr/local/bin/docker-compose

  tasks:
    - name: install docker
      yum:
        name: "{{docker_package}}"
        state: present

    - name: start and enable docker
      service:
        name: "{{docker_service}}"
        state: started
        enabled: yes
      notify: restart docker

    - name: install docker_compose
      get_url:
        url: "{{docker_compose_url}}"
        dest: "{{docker_compose_path}}"
        mode: 'u=rwx,g=rx,o=r'

    - name: install nginx app_server
      package:
        name: nginx
        state: present
      
    - name: start and enable docker
      service: 
        name: nginx
        state: started
        enabled: yes

         
  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted



